### ISSUE TITLE
Inventing the Wheel, again!

### ISSUE THREAD

**Issue by ozantopal** [NisanurBulut/SayHiCode#37]
Take a look of that repository: https://github.com/RITIKHARIANI/Finance-Logger-TypeScript/ in case of you didn't realize its existence. Happy coding!

**Comment by ozantopal** [comment]
@RITIKHARIANI may wanna take a look.

**Comment by RITIKHARIANI** [comment]
@ozantopal , Thank You, that was my application in TypeScript as well

**Comment by NisanurBulut** [comment]
@ozantopal The sayhicode repository is the practice repository.I practiced the net ninja tutorial videos.There is a related link under the title of helpfull websites.
